PYTHON=python
UV=uv
TOML=pyproject.toml

.PHONY: install test venv init run 

install:
	$(UV) pip install -r $(TOML)

test:
	pytest -q 

venv:
	$(UV) venv .

init: 
	$(UV) venv .
	$(UV) pip install -r $(TOML)

run:
	$(UV) sync
	$(UV) run {{ terminal_command }}

