PYTHON=python
ENV_FILE=environment.yml

.PHONY: env-create env-update install run init

env-create:
	conda env create -f $(ENV_FILE)

env-update:
	conda env update -f $(ENV_FILE) --prune

install:
	eval "$(conda shell.bash hook)" 
	conda activate {{ project_name }}
	$(PYTHON) -m pip install -e .

init:
	eval "$(conda shell.bash hook)" 
	conda activate {{ project_name }}
	$(PYTHON) -m pip install .

run:
	eval "$(conda shell.bash hook)" 
	conda activate {{ project_name }}
	$(PYTHON) -m {{ project_name }}
