PYTHON=python
ENV_FILE=environment.yml
ENV={{ project_name }}

.PHONY: env-create env-update install run init

env-create:
	conda env create -f $(ENV_FILE)

env-update:
	conda env update -f $(ENV_FILE) --prune

install:
	conda run -n $(ENV) python -m pip install -e .

init:
	conda run -n $(ENV) python -m pip install -e .

run:
	conda run -n $(ENV) python -m {{ project_name }}
